# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

fib_one = 1
fib_two = 1
nxt_fib = fib_one + fib_two
sum_fib = 0

while nxt_fib < 4000000:
  nxt_fib = fib_one + fib_two
  if nxt_fib % 2 == 0:
    sum_fib += nxt_fib
  fib_one = fib_two
  fib_two = nxt_fib
  print(nxt_fib)
print("=" * 25)
print(sum_fib)